apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: vmrule
  namespace: monitoring-system
spec:
  groups:
    - name: HighErrorRate
      rules:
        - alert: todo error rate is high
          expr: sum(rate(todo_api_requests_total{code="500"}[5m]))/sum(rate(todo_api_requests_total[5m])) > 0.3
          for: 60s
          labels:
            severity: critical
            job:  "{{ $labels.job }}"
          annotations:
            value: "{{ $value }}"
            description: 'todo error rate is high'
