apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: kube-state-metrics
        args:
        - --metric-labels-allowlist
        - namespaces=[team]
