apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: todo-agent
  namespace: todo
spec:
  replicaCount: 1
  remoteWrite:
    - url: "http://vmsingle-database.monitoring-system.svc:8429/api/v1/write"
  podScrapeNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: todo
  scrapeInterval: 30s
