---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-setting
  namespace: todo
type: Opaque
stringData:
  alertmanager.yaml: |
    route:
      receiver: slack
    receivers:
      - name: 'slack'
        slack_configs:
          - api_url: 'https://hooks.slack.com/services/xxxxx'
            channel: '#xxxxx'
            text: "{{ .CommonAnnotations.summary }}"
            send_resolved: true
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: alertmanager
  namespace: todo
spec:
  replicaCount: 1
  configSecret: alertmanager-setting
