apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vmagent.yaml
  - vmsingle.yaml
  - rules/argocd.yaml
  - rules/kube-state-metrics.yaml
  - rules/kubernetes.yaml
  - rules/node-exporter.yaml
  - grafana.yaml
  - datasource.yaml
