apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: database
  namespace: monitoring-system
spec:
  retentionPeriod: "1"
  removePvcAfterDelete: true
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
