apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zoetrope/k8s-hands-on.git
    targetRevision: main
    path: manifests/contour
  destination:
    server: https://kubernetes.default.svc
    namespace: projectcontour
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
