apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app.kubernetes.io/name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: todo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todo
    spec:
      containers:
        - name: todo
          image: todo:0.1.0
          command: ["/todo"]
