apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - service.yaml
  - scrape.yaml
  - request.yaml
  - vmagent.yaml
  - vmalert.yaml
  - vmalertmanager.yaml
  - vmrule.yaml
