apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argocd
  namespace: argocd
spec:
  routes:
  - services:
    - name: argocd-server
      port: 80
    pathRewritePolicy:
      replacePrefix:
      - replacement: /
