apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: grafana
  namespace: grafana
spec:
  routes:
  - services:
    - name: grafana-service
      port: 3000
    pathRewritePolicy:
      replacePrefix:
      - replacement: /
