apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: todo
  namespace: todo
spec:
  routes:
    - services:
        - name: todo
          port: 80
      pathRewritePolicy:
        replacePrefix:
          - replacement: /
